Лабораторная работа 1. Яровенко Максим, ИУ5Ц-102Б. Вариант 22


# **Условия задачи по варианту**

Используем data.frame Computers:

In [63]:
Data<-read.csv("Computers.csv",sep=",")
View(Data)

X    price speed hd   ram screen cd  multi premium ads trend
1     1   1499  25     80   4  14     no  no    yes     94  1    
2     2   1795  33     85   2  14     no  no    yes     94  1    
3     3   1595  25    170   4  15     no  no    yes     94  1    
4     4   1849  25    170   8  14     no  no    no      94  1    
5     5   3295  33    340  16  14     no  no    yes     94  1    
6     6   3695  66    340  16  14     no  no    yes     94  1    
7     7   1720  25    170   4  14     yes no    yes     94  1    
8     8   1995  50     85   2  14     no  no    yes     94  1    
9     9   2225  50    210   8  14     no  no    yes     94  1    
10   10   2575  50    210   4  15     no  no    yes     94  1    
11   11   2195  33    170   8  15     no  no    yes     94  1    
12   12   2605  66    210   8  14     no  no    yes     94  1    
13   13   2045  50    130   4  14     no  no    yes     94  1    
14   14   2295  25    245   8  14     no  no    yes     94  1    
15   15   2699  50    212   8  14     no  no    yes     94  1    
16   16   2225  50    130   4  14     no  no    yes     94  1    
17   17   1595  33     85   2  14     no  no    yes     94  1    
18   18   2325  33    210   4  15     no  no    yes     94  1    
19   19   2095  33    250   4  15     no  no    yes     94  1    
20   20   4395  66    452   8  14     no  no    yes     94  1    
21   21   1695  33    130   4  14     no  no    yes     94  1    
22   22   2795  66    130   4  14     no  no    yes     94  1    
23   23   2895  25    340  16  14     no  no    yes     94  1    
24   24   2875  50    210   4  17     no  no    yes     94  1    
25   25   4195  50    452   8  14     no  no    yes     94  1    
26   26   1290  33     80   2  14     no  no    yes     94  1    
27   27   1975  33    130   4  14     no  no    yes     94  1    
28   28   3995  33    452   8  14     no  no    yes     94  1    
29   29   3095  33    340  16  14     no  no    yes     94  1    
30   30   3244  66    245   8  14     no  no    yes     94  1    
⋮    ⋮    ⋮     ⋮     ⋮    ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
6230 6230 2344   66    850 16  15     yes no    yes     39  35   
6231 6231 2890  100   1200 24  17     yes no    yes     39  35   
6232 6232 2390   66    850 16  17     yes no    yes     39  35   
6233 6233 1495   66    528  8  14     no  no    yes     39  35   
6234 6234 1844  100    528  8  14     no  no    yes     39  35   
6235 6235 1699   66    630  8  15     no  no    no      39  35   
6236 6236 3290   75   1600 32  17     yes no    yes     39  35   
6237 6237 2790   66   1200 24  17     yes no    yes     39  35   
6238 6238 2845  100   1600 24  15     yes no    yes     39  35   
6239 6239 1744   66    528  8  14     no  no    yes     39  35   
6240 6240 3095  100   1600 32  15     yes no    yes     39  35   
6241 6241 1595  100    528  8  14     no  no    yes     39  35   
6242 6242 2254  100    850 16  15     yes no    yes     39  35   
6243 6243 2723  100   1200 24  15     yes yes   yes     39  35   
6244 6244 2745   66   1600 24  15     yes no    yes     39  35   
6245 6245 3054   75   1600 32  15     yes no    yes     39  35   
6246 6246 2744   66   1200 24  15     yes no    yes     39  35   
6247 6247 1554   66    528  8  14     no  no    yes     39  35   
6248 6248 1654  100    528  8  14     no  no    yes     39  35   
6249 6249 2623   66   1200 24  15     yes yes   yes     39  35   
6250 6250 2095   66    850 16  15     yes no    yes     39  35   
6251 6251 2495   66   1200 24  15     yes no    yes     39  35   
6252 6252 2995   66   1600 32  15     yes no    yes     39  35   
6253 6253 1690   66   1200  8  14     no  no    yes     39  35   
6254 6254 2154   66    850 16  15     yes no    yes     39  35   
6255 6255 1690  100    528  8  15     no  no    yes     39  35   
6256 6256 2223   66    850 16  15     yes yes   yes     39  35   
6257 6257 2654  100   1200 24  15     yes no    yes     39  35   
6258 6258 2195  100    850 16  15     yes no 

Требуется развернуть КИС, включающую в себя:
- серверные станции $С_1$;
- рабочие станции аналитиков и менеджеров $C_2$;
- рабочие станции обслуживающего персонала $C_3$;
- станции сопряжения с видео, аудио оборудованием $C_4$.

Станции одного типа считать одинаковыми по всем параметрам.
Требования к каждому типу станций перечислены в таблицах ниже:

In [64]:
set.seed(13)
Count_low<-data.frame()
for (i in c(1:50)){
    Count_low<-rbind(Count_low, c(i,sample(c(3:6),1), sample(c(6:20),1), sample(c(1:20),1), sample(c(1:9),1)))}
colnames(Count_low)<-c("Вариант","Количество С1 >=","Количество С2 >=", "Количество С3 >=", "Количество С4 >=")
View(Count_low)

Вариант Количество С1 >= Количество С2 >= Количество С3 >= Количество С4 >=
1   1      6                 8                5               6               
2   2      6                11                4               8               
3   3      5                 6               10               7               
4   4      5                10               12               1               
5   5      4                13               15               1               
6   6      6                 6               11               4               
7   7      6                12               14               5               
8   8      5                20                3               5               
9   9      4                 9                2               1               
10 10      4                 8               19               6               
11 11      6                 6               12               8               
12 12      4                15                7               2               
13 13      3                19               18               3               
14 14      3                 7               14               1               
15 15      6                14                1               6               
16 16      5                 6               16               3               
17 17      5                11                8               9               
18 18      6                 6               19               8               
19 19      3                12                5               9               
20 20      5                11               14               9               
21 21      6                 8                5               5               
22 22      3                11                3               1               
23 23      4                 6                8               4               
24 24      4                 6               14               8               
25 25      6                13                7               9               
26 26      4                 8               13               5               
27 27      4                11               13               2               
28 28      3                16               18               9               
29 29      4                12                3               2               
30 30      4                11               15               5               
31 31      5                 9                2               9               
32 32      3                 8                7               3               
33 33      6                20                8               7               
34 34      6                 8               16               5               
35 35      5                16               13               4               
36 36      3                17               17               3               
37 37      4                10                5               8               
38 38      6                14                8               1               
39 39      5                16               14               9               
40 40      6                13               19               2               
41 41      5                12                1               7               
42 42      6                13               17               1               
43 43      4                20                4               7               
44 44      6                13               17               9               
45 45      5                17                9               3               
46 46      4                20                7               3               
47 47      3                13               10               7               
48 48      6                11               15               6               
49 49      6                16               13               2               
50 50      5                 8                9      

In [65]:
Count_up<-data.frame()
for (i in c(1:50)){
    Count_up<-rbind(Count_up, c(i,Count_low[i,2]+sample(c(3:6),1), Count_low[i,3]+sample(c(6:20),1),
                                          Count_low[i,4]+sample(c(1:20),1), Count_low[i,5]+sample(c(1:9),1)))}
colnames(Count_up)<-c("Вариант","Количество С1 <=","Количество С2 <=", "Количество С3 <=", "Количество С4 <=")
View(Count_up)

Вариант Количество С1 <= Количество С2 <= Количество С3 <= Количество С4 <=
1   1      10               14                9               15              
2   2      11               21               17               10              
3   3       8               22               21                8              
4   4       9               25               29                8              
5   5       7               22               33                8              
6   6      10               22               15               13              
7   7      12               18               15                8              
8   8       9               32               18               14              
9   9       9               19               18               10              
10 10       7               15               33               13              
11 11       9               20               15               14              
12 12       9               33               11                5              
13 13       6               25               22                8              
14 14       7               13               26                3              
15 15      11               30               14               13              
16 16      10               22               31                6              
17 17      11               18               25               11              
18 18      12               26               25               17              
19 19       9               32                9               12              
20 20       9               25               16               15              
21 21      12               25               23               12              
22 22       9               31                5               10              
23 23       7               21               21               11              
24 24       7               25               20                9              
25 25      11               21                8               13              
26 26       7               28               30               11              
27 27       8               31               24                8              
28 28       9               22               19               11              
29 29       8               20               18                9              
30 30       7               24               22               14              
31 31      11               25               20               12              
32 32       7               19               26                8              
33 33       9               37               27               16              
34 34      12               19               18               10              
35 35       9               33               17                6              
36 36       7               36               34               12              
37 37       7               25               24                9              
38 38      10               33               15                7              
39 39       8               23               23               15              
40 40      12               33               32                6              
41 41       9               27               10               14              
42 42       9               28               28                4              
43 43       8               30               10               10              
44 44      12               23               23               17              
45 45       8               29               27               11              
46 46       7               32               24               12              
47 47       8               32               15               10              
48 48       9               24               19               12              
49 49      12               32               30                8              
50 50      10               16               22      

Самостоятельно сформулировать ограничения (максимальные или минимальные) на общую стоимость развертывания всей технической инфраструктуры КИС, возможные ограничения на суммарную стоимость отдельных типов станций ($C_1$, $C_2$, $C_3$, $C_4$), нижние ограничения на частоту процессора для $C_1, C_2$, другие приемлемые ограничения.

Построить регрессионную модель для оценки стоимости отдельной рабочей станции в зависимости от частоты процессора, объема оперативной памяти, объема винчестера.

In [66]:
Res<-lm(price~speed+ram+hd, Data)

In [67]:
Res


Call:
lm(formula = price ~ speed + ram + hd, data = Data)

Coefficients:
(Intercept)        speed          ram           hd  
  1492.1775       5.8112      78.2357      -0.5357  


In [68]:
g<-predict(Res,Data)
View(data.frame(Data$price, g))

Data.price g       
1    1499       1907.542
2    1795       1794.882
3    1595       1859.328
4    1849       2172.271
5    3295       2753.573
6    3695       2945.343
7    1720       1859.328
8    1995       1893.672
9    2225       2296.121
10   2575       1983.179
11   2195       2218.760
12   2605       2389.100
13   2045       2026.036
14   2295       2132.092
15   2699       2295.050
16   2225       2026.036
17   1595       1794.882
18   2325       1884.388
19   2095       1862.960
20   4395       2259.456
21   1695       1927.246
22   2795       2119.015
23   2895       2707.084
24   2875       1983.179
25   4195       2166.477
26   1290       1797.561
27   1975       1927.246
28   3995       2067.687
29   3095       2753.573
30   3244       2370.350
⋮    ⋮          ⋮       
6230 2344       2672.125
6231 2890       3308.089
6232 2390       2672.125
6233 1495       2218.741
6234 1844       2416.322
6235 1699       2164.098
6236 3290       3574.407
6237 2790       3110.509
6238 2845       3093.801
6239 1744       2218.741
6240 3095       3719.687
6241 1595       2416.322
6242 2254       2869.706
6243 2723       3308.089
6244 2745       2896.221
6245 3054       3574.407
6246 2744       3110.509
6247 1554       2218.741
6248 1654       2416.322
6249 2623       3110.509
6250 2095       2672.125
6251 2495       3110.509
6252 2995       3522.106
6253 1690       1858.737
6254 2154       2672.125
6255 1690       2416.322
6256 2223       2672.125
6257 2654       3308.089
6258 2195       2869.706
6259 2490       2869.706

Построить двухуровневую задачу проектирования КИС. На первом уровне оптимизируется стоимость всей системы в целом. На нижнем уровне по сегментам оптимизируется: $C_1$ - суммарная производительность (speed, ram) всего серверного оборудования, $C_2$ - суммарный объем долговременной (винчестер) и оперативной памяти. При необходимости провести нормализацию конструктивных параметров. Остальные критерии оптимизации, коэффициенты важности выбрать с позиции системного администратора самостоятельно.



На исходном датафрейме выбрать варианты, удовлетворяющие условиям работоспособности, на полученном множестве выбрать Парето-оптимальные решения, из множества эффективных по Парето решений подобрать варианты, которые наиболее близки к решениям задачи оптимизации.

Сделать окончательные выводы:
- сегмент $C_1$: количество компьютеров, номер варианта (X) из датафрейма Data;
- сегмент $C_2$: количество компьютеров, номер варианта (X) из датафрейма Data;
- сегмент $C_3$: количество компьютеров, номер варианта (X) из датафрейма Data;
- сегмент $C_4$: количество компьютеров, номер варианта (X) из датафрейма Data.

# **Выполнение работы**

У нас есть 4 сегмента: С1, С2, С3, С4. Требуется выбрать в первый сегмент от ***3*** до ***9*** компьютеров, во второй сегмент от ***11*** до ***31***, в третьем от ***3*** до ***5***, в четвертом от ***1*** до ***10***. Крайние значения включены.

Стоимость отдельного компьютера от конструктивных параметров $speed, ram, hd$ выражена ранее через регрессионную зависимость (можно брать необязательно от этих параметров, точность можно оценить через коэффициент детерминации) :

$$ price = 1492.1775+5.8112\cdot speed+78.2357\cdot ram-0.5357\cdot hd$$

Добавим несколько ограничений нижнего уровня:
 - суммарная стоимость компьютеров сегмента $C_1$ должна быть не более 10000 у.е.
 - суммарная производительность $C_2$ не менее 300 (считаем аддитивной характеристикой от количества входящих ПК)
 - суммарная производительность $C_3$ не менее 200 (считаем аддитивной характеристикой от количества входящих ПК)
 - суммарная стоимость компьютеров сегмента $C_4$ должна быть не более 5000 у.е.


Обозначим $N_1$ - количество компьютеров 1 сегмента, $N_2$ - количество компьютеров второго сегмента,
$N_3$ - количество компьютеров 3 сегмента, $N_4$ - количество компьютеров 4 сегмента,

Критерий верхнего уровня:


$$H_1 = N_1\cdot price_1+N_2\cdot price_2+N_3\cdot price_3+N_4\cdot price_4\rightarrow \min$$



После подстановки регрессионных зависимостей получаем:


$$H_1 = 1492.1775N_1+5.8112\cdot speed_1\cdot N_1+78.2357\cdot ram_1\cdot N_1-0.5357\cdot hd_1\cdot N_1+1492.1775N_2+5.8112\cdot speed_2\cdot N_2+78.2357\cdot ram_2\cdot N_2-0.5357\cdot hd_2\cdot N_2  +1492.1775N_3+5.8112\cdot speed_2\cdot N_3+78.2357\cdot ram_3\cdot N_3-0.5357\cdot hd_3\cdot N_3
+1492.1775N_4+5.8112\cdot speed_4\cdot N_4+78.2357\cdot ram_4\cdot N_4-0.5357\cdot hd_4\cdot N_2$$



Обозначим:


$$1492.1775N_1 = x_1,$$
$$3\cdot1492.1775\leq x_1\leq 9\cdot 1492.1775$$
$$speed_1\cdot N_1 = x_2$$
$$ram_1\cdot N_1 = x_3$$
$$ hd_1\cdot N_1 = x_4$$

$$1492.1775N_2 = x_5,$$
$$11\cdot 1492.1775\leq x_5\leq 31\cdot 1492.1775$$
$$speed_2\cdot N_2 = x_6$$
$$ram_2\cdot N_2 = x_7$$
$$hd_2\cdot N_2 = x_8$$

$$1492.1775N_3 = x_9,$$
$$3\cdot1492.1775\leq x_9\leq 5\cdot 1492.1775$$
$$speed_3\cdot N_3 = x_{10}$$
$$ram_3\cdot N_3 = x_{11}$$
$$ hd_3\cdot N_3 = x_{12}$$

$$1492.1775N_4 = x_{13},$$
$$1\cdot1492.1775\leq x_13\leq 10\cdot 1492.1775$$
$$speed_4\cdot N_4 = x_{14}$$
$$ram_4\cdot N_4 = x_{15}$$
$$ hd_4\cdot N_4 = x_{16}$$

Для нахождения ограничений на остальные $x_i$ можно взять усредненные характеристики:

In [69]:
mean(Data$speed)
mean(Data$ram)
mean(Data$hd)

[1] 52.01102

[1] 8.286947

[1] 416.6017

Соответственно остальные ограничения следующие:


$$3\cdot 52.0110241252596\leq x_2\leq 9\cdot 52.0110241252596$$
$$3\cdot 8.28694679661288\leq x_3\leq 9\cdot 8.28694679661288$$
$$3\cdot 416.601693561272\leq x_4\leq 9\cdot 416.601693561272$$

$$11\cdot 52.0110241252596\leq x_6\leq 31\cdot 52.0110241252596$$
$$11\cdot 8.28694679661288\leq x_7\leq 31\cdot 8.28694679661288$$
$$11\cdot 416.601693561272\leq x_8\leq 31\cdot 416.601693561272$$

$$3\cdot 52.0110241252596\leq x_{10}\leq 5\cdot 52.0110241252596$$
$$3\cdot 8.28694679661288\leq x_{11}\leq 5\cdot 8.28694679661288$$
$$3\cdot 416.601693561272\leq x_{12}\leq 5\cdot 416.601693561272$$

$$1\cdot 52.0110241252596\leq x_{14}\leq 10\cdot 52.0110241252596$$
$$1\cdot 8.28694679661288\leq x_{15}\leq 10\cdot 8.28694679661288$$
$$1\cdot 416.601693561272\leq x_{16}\leq 10\cdot 416.601693561272$$



Учтем ограничения нижнего уровня:

$$N_1\cdot price_1\leq 10000\Rightarrow x_1+5.8112\cdot x_2+78.2357\cdot x_3-0.5357\cdot x_4\leq 10000$$
$$N_2\cdot speed_2\geq 300\Rightarrow x_6\geq 300$$
$$N_3\cdot speed_3\geq 200\Rightarrow x_{10}\geq 200$$
$$N_4\cdot price_4\leq 5000\Rightarrow x_{13}+5.8112\cdot x_{14}+78.2357\cdot x_{15}-0.5357\cdot x_{16}\leq 5000$$

Для оптимизации на нижнем уровне требуется проведение нормализации, т.к. иначе в свертке будут складываться разные физические единицы измерения (частота процессора, объем оперативной памяти).

$$\bar x_2=\frac{x_2}{max (N_1) \cdot max(speed)} = \frac{x_2}{9 \cdot 100} = \frac{x_2}{900}$$

$$\bar x_3=\frac{x_3}{max (N_1) \cdot max(ram)} = \frac{x_3}{9 \cdot 32} = \frac{x_3}{288}$$


$$\bar x_7=\frac{x_7}{max (N_2) \cdot max(ram)} = \frac{x_7}{31 \cdot 32} = \frac{x_7}{992}$$

$$\bar x_8=\frac{x_8}{max (N_2) \cdot max(hd)} = \frac{x_8}{31 \cdot 2100} = \frac{x_8}{65100}$$

$$\bar x_{11}=\frac{x_{11}}{max (N_3) \cdot max(ram)} = \frac{x_{11}}{5 \cdot 32} = \frac{x_{11}}{160}$$

$$\bar x_{12}=\frac{x_{12}}{max (N_3) \cdot max(hd)} = \frac{x_{12}}{5 \cdot 2100} = \frac{x_{12}}{10500}$$

$$\bar x_{15}=\frac{x_{15}}{max (N_4) \cdot max(ram)} = \frac{x_{15}}{10 \cdot 32} = \frac{x_{15}}{320}$$

$$\bar x_{16}=\frac{x_{16}}{max (N_4) \cdot max(hd)} = \frac{x_{16}}{10 \cdot 2100} = \frac{x_{16}}{21000}$$


In [70]:
max(Data$speed)
max(Data$ram)
max(Data$hd)

[1] 100

[1] 32

[1] 2100

Сформулируем также частные критерии оптимизации на нижнем уровне:
- суммарная производительность (speed, ram) в сегменте $C_1$ максимизируется:

$$W_1 = 0.7\cdot \frac{x_2}{900}+0.3 \cdot \frac{x_3}{288}\rightarrow \max$$

- суммарный объем памяти в сегменте $C_2$ максимизируется:

$$W_2=0.6\cdot \frac{x_7}{992}+0.4\cdot \frac{x_8}{65100}\rightarrow\max$$

- суммарный объем памяти в сегменте $C_3$ максимизируется:

$$W_3=0.5\cdot \frac{x_{11}}{160}+0.5\cdot \frac{x_{12}}{10500}\rightarrow\max$$

- суммарный объем памяти в сегменте $C_3$ максимизируется:

$$W_4=0.3\cdot \frac{x_{15}}{320}+0.7\cdot \frac{x_{16}}{21000}\rightarrow\max$$


Формируем критерий нижнего уровня:


$$H_2=0.25\cdot W_1+0.25\cdot W_2+0.25\cdot W_3+0.25\cdot W_4=0.7\cdot 0.25\cdot\frac{x_2}{900}+0.3\cdot 0.25 \cdot \frac{x_3}{288}+0.6\cdot 0.25\cdot \frac{x_7}{992}+0.4\cdot 0.25\cdot \frac{x_8}{65100}  +0.5\cdot 0.25\cdot \frac{x_{11}}{160}+0.5\cdot 0.25\cdot \frac{x_{12}}{10500} +  0.3\cdot 0.25\cdot\frac{x_{15}}{320}+0.7\cdot 0.25\cdot \frac{x_{16}}{21000}
\rightarrow\max$$

Окончательно получаем:


$$H_1 = x_1+5.8112\cdot x_2 +78.2357\cdot x_3-0.5357\cdot x_4 + x_5+
5.8112\cdot x_6+78.2357\cdot x_7-0.5357\cdot x_8  +x_9+5.8112\cdot x_{10}+
78.2357\cdot x_{11}-0.5357\cdot x_{12}
+x_{13}+5.8112\cdot x_{14} + 78.2357\cdot x_{15}-0.5357\cdot x_{16} \rightarrow \min$$


$$H_2=0.7\cdot 0.25\cdot\frac{x_2}{900}+0.3\cdot 0.25 \cdot \frac{x_3}{288}+0.6\cdot 0.25\cdot \frac{x_7}{992}+0.4\cdot 0.25\cdot \frac{x_8}{65100}  +0.5\cdot 0.25\cdot \frac{x_{11}}{160}+0.5\cdot 0.25\cdot \frac{x_{12}}{10500} +  0.3\cdot 0.25\cdot\frac{x_{15}}{320}+0.7\cdot 0.25\cdot \frac{x_{16}}{21000}
\rightarrow\max$$


$$3\cdot 52.0110241252596\leq x_2\leq 9\cdot 52.0110241252596$$
$$3\cdot 8.28694679661288\leq x_3\leq 9\cdot 8.28694679661288$$
$$3\cdot 416.601693561272\leq x_4\leq 9\cdot 416.601693561272$$

$$11\cdot 52.0110241252596\leq x_6\leq 31\cdot 52.0110241252596$$
$$11\cdot 8.28694679661288\leq x_7\leq 31\cdot 8.28694679661288$$
$$11\cdot 416.601693561272\leq x_8\leq 31\cdot 416.601693561272$$

$$3\cdot 52.0110241252596\leq x_{10}\leq 5\cdot 52.0110241252596$$
$$3\cdot 8.28694679661288\leq x_{11}\leq 5\cdot 8.28694679661288$$
$$3\cdot 416.601693561272\leq x_{12}\leq 5\cdot 416.601693561272$$

$$1\cdot 52.0110241252596\leq x_{14}\leq 10\cdot 52.0110241252596$$
$$1\cdot 8.28694679661288\leq x_{15}\leq 10\cdot 8.28694679661288$$
$$1\cdot 416.601693561272\leq x_{16}\leq 10\cdot 416.601693561272$$


$$x_1+5.8112\cdot x_2+78.2357\cdot x_3-0.5357\cdot x_4\leq 10000$$
$$x_6\geq 300$$
$$x_{10}\geq 200$$
$$x_{13}+5.8112\cdot x_{14}+78.2357\cdot x_{15}-0.5357\cdot x_{16}\leq 5000$$

Полученную оптимизационную задачу решаем методом последовательных уступок, как показано в примере 2 лекции.
Таким образом, находим приемлемые значения $x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8$


$$N_1=\left\lfloor \frac{x_1}{1492.1775}\right\rfloor, N_2=\left\lfloor \frac{x_5}{1492.1775}\right\rfloor$$

$$N_3=\left\lfloor \frac{x_9}{1492.1775}\right\rfloor, N_4=\left\lfloor \frac{x_{13}}{1492.1775}\right\rfloor$$

$$speed_1=\frac{x_2}{N_1}, ram_1=\frac{x_3}{N_1}, hd_1=\frac{x_4}{N_1}$$

$$speed_2=\frac{x_6}{N_2}, ram_2=\frac{x_7}{N_2}, hd_2=\frac{x_8}{N_2}$$

$$speed_3=\frac{x_{10}}{N_3}, ram_3=\frac{x_{11}}{N_3}, hd_3=\frac{x_{12}}{N_3}$$

$$speed_4=\frac{x_{14}}{N_4}, ram_2=\frac{x_{15}}{N_4}, hd_4=\frac{x_{16}}{N_4}$$

Полученные кортежи $<speed_1, ram_1, hd_1>, <speed_2, ram_2, hd_2>$ определяют координаты идеальных точек для каждого сегмента.

После этого учитываем условия работоспособности, проводим Парето оптимизацию на множестве возможных технических вариантов из датафрейма "Computers.csv". Из полученных технических решений выбираем наиболее близкие к каждой идеальной точки внутри каждого сегмента.

# **Код**

In [71]:
H1<-function(x1,x2,x3,x4, x5,x6,x7,x8, x9,x10,x11,x12, x13,x14,x15,x16){return(x1 + 5.8112*x2+78.2357*x3-0.5357*x4
                                                                                  + x5+5.8112*x6+78.2357*x7-0.5357*x8
                                                                                  + x9+5.8112*x10+78.2357*x11-0.5357*x12
                                                                                  + x13+5.8112*x14+78.2357*x15-0.5357*x16)}

In [72]:
H2<-function(x2,x3,x7,x8,x11, x12,x15,x16){return(0.7*0.25*x2/900 + 0.3*0.25*x3/288 + 0.6*0.25*x7/992 + 0.4*0.25*x8/65100 + 0.5*0.25*x11/160
 +0.5*0.25*x12/10500 + 0.3*0.25*x15/320 +0.7*0.25*x16/21000 )}

In [73]:
W1<-function(x2,x3){return(0.7*x2/900 + 0.3*x3/288 )}
W2<-function(x7,x8){return(0.6*x7/992 + 0.4*x8/65100 )}
W3<-function(x11,x12){return(0.5*x11/160 + 0.5*x12/10500 )}
W4<-function(x15,x16){return(0.3*x15/320 + 0.7*x16/21000 )}

In [74]:
Data_funcs <-data.frame(Data,
                        W1(Data$speed, Data$ram), W2(Data$ram, Data$hd),
                        W3(Data$ram, Data$hd),W4(Data$ram, Data$hd),
                        H1(1492.1775,Data$speed, Data$ram, Data$hd, 1492.1775,Data$speed, Data$ram, Data$hd,
                          1492.1775,Data$speed, Data$ram, Data$hd, 1492.1775,Data$speed, Data$ram, Data$hd),
                        H2(Data$speed, Data$ram, Data$ram, Data$hd, Data$ram, Data$hd, Data$ram, Data$hd)
                       )

In [75]:
head(Data_funcs)

X price speed hd  ram screen cd multi premium ads trend
1 1 1499  25     80  4  14     no no    yes     94  1    
2 2 1795  33     85  2  14     no no    yes     94  1    
3 3 1595  25    170  4  15     no no    yes     94  1    
4 4 1849  25    170  8  14     no no    no      94  1    
5 5 3295  33    340 16  14     no no    yes     94  1    
6 6 3695  66    340 16  14     no no    yes     94  1    
  W1.Data.speed..Data.ram. W2.Data.ram..Data.hd. W3.Data.ram..Data.hd.
1 0.02361111               0.002910906           0.01630952           
2 0.02775000               0.001731951           0.01029762           
3 0.02361111               0.003463902           0.02059524           
4 0.02777778               0.005883257           0.03309524           
5 0.04233333               0.011766513           0.06619048           
6 0.06800000               0.011766513           0.06619048           
  W4.Data.ram..Data.hd.
1 0.006416667          
2 0.004708333          
3 0.009416667          
4 0.013166667          
5 0.026333333          
6 0.026333333          
  H1.1492.1775..Data.speed..Data.ram..Data.hd..1492.1775..Data.speed..
1  7630.177                                                           
2  7179.536                                                           
3  7437.325                                                           
4  8689.096                                                           
5 11014.321                                                           
6 11781.400                                                           
  H2.Data.speed..Data.ram..Data.ram..Data.hd..Data.ram..Data.hd..
1 0.01231205                                                     
2 0.01112198                                                     
3 0.01427173                                                     
4 0.01998073                                                     
5 0.03665591                                                     
6 0.04307258

In [76]:
colnames(Data_funcs)<-c("X","price","speed","hd","ram","screen","cd", "multi", "premium", "ads","trend",
                  "W1","W2","W3","W4","H1","H2")
head(Data_funcs)

X price speed hd  ram screen cd multi premium ads trend W1        
1 1 1499  25     80  4  14     no no    yes     94  1     0.02361111
2 2 1795  33     85  2  14     no no    yes     94  1     0.02775000
3 3 1595  25    170  4  15     no no    yes     94  1     0.02361111
4 4 1849  25    170  8  14     no no    no      94  1     0.02777778
5 5 3295  33    340 16  14     no no    yes     94  1     0.04233333
6 6 3695  66    340 16  14     no no    yes     94  1     0.06800000
  W2          W3         W4          H1        H2        
1 0.002910906 0.01630952 0.006416667  7630.177 0.01231205
2 0.001731951 0.01029762 0.004708333  7179.536 0.01112198
3 0.003463902 0.02059524 0.009416667  7437.325 0.01427173
4 0.005883257 0.03309524 0.013166667  8689.096 0.01998073
5 0.011766513 0.06619048 0.026333333 11014.321 0.03665591
6 0.011766513 0.06619048 0.026333333 11781.400 0.04307258

In [77]:
summary(Data_funcs)

       X            price          speed              hd        
 Min.   :   1   Min.   : 949   Min.   : 25.00   Min.   :  80.0  
 1st Qu.:1566   1st Qu.:1794   1st Qu.: 33.00   1st Qu.: 214.0  
 Median :3130   Median :2144   Median : 50.00   Median : 340.0  
 Mean   :3130   Mean   :2220   Mean   : 52.01   Mean   : 416.6  
 3rd Qu.:4694   3rd Qu.:2595   3rd Qu.: 66.00   3rd Qu.: 528.0  
 Max.   :6259   Max.   :5399   Max.   :100.00   Max.   :2100.0  
      ram             screen           cd               multi          
 Min.   : 2.000   Min.   :14.00   Length:6259        Length:6259       
 1st Qu.: 4.000   1st Qu.:14.00   Class :character   Class :character  
 Median : 8.000   Median :14.00   Mode  :character   Mode  :character  
 Mean   : 8.287   Mean   :14.61                                        
 3rd Qu.: 8.000   3rd Qu.:15.00                                        
 Max.   :32.000   Max.   :17.00                                        
   premium               ads            t

In [78]:
install.packages("lpSolve")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [79]:
library(lpSolve)

In [80]:
objective.in<-c(1, 5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357,
                1,5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357)
const.mat<-matrix(c(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,

                    0, 0.7*0.25/900, 0.3*0.25/288, 0, 0, 0, 0.6*0.25/992, 0.4*0.2565100, 0, 0, 0.5*0.25/160, 0.5*0.25/10500, 0, 0, 0.3*0.25/320, 0.7*0.25/21000
                  ), nrow=33, byrow=TRUE)
const.dir<-c(">=",  "<=", ">=",  "<=",   ">=",  "<=",  ">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",
             "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",
             "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",    ">=")
const.rhs<-c(3*1492.1775, 9*1492.1775, 3*52.0110241252596, 9*52.0110241252596, 3*8.28694679661288, 9*8.28694679661288,
            3*416.601693561272, 9*416.601693561272, 11*1492.1775, 31*1492.1775, 11*52.0110241252596, 31*52.0110241252596,
            11*8.28694679661288, 31*8.28694679661288, 11*416.601693561272, 31*416.601693561272, 3*1492.1775, 5*1492.1775,
            3*52.0110241252596, 5*52.0110241252596, 3*8.28694679661288, 5*8.28694679661288,
            3*416.601693561272, 5*416.601693561272, 1*1492.1775, 10*1492.1775, 1*52.0110241252596, 10*52.0110241252596,
            1*8.28694679661288, 10*8.28694679661288, 1*416.601693561272, 10*416.601693561272, 1)
Res<-lp("min", objective.in, const.mat, const.dir, const.rhs)

Warning message in rbind(const.mat, const.dir.num, const.rhs):
“number of columns of result is not a multiple of vector length (arg 2)”


In [81]:
HH1<-function(p){return(sum(c(1, 5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357, 1, 5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357)*p))}
HH2<-function(p){return(sum(c(0, 0.7*0.25/900, 0.3*0.25/288, 0, 0, 0, 0.6*0.25/992, 0.4*0.2565100, 0, 0, 0.5*0.25/160, 0.5*0.25/10500, 0, 0, 0.3*0.25/320, 0.7*0.25/21000)*p))}

In [82]:
Res$solution

[1]  4476.532500   156.033072    24.860840  3749.415242 16413.952500
 [6]   572.121265    91.156415 12914.652500  4476.532500   156.033072
[11]    24.860840  2083.008468  1492.177500    52.011024     8.286947
[16]  4166.016936

In [83]:
HH1(Res$solution);
HH2(Res$solution)

[1] 31695.12

[1] 1325.226

In [84]:
objective.in<-c(0, 0.7*0.25/900, 0.3*0.25/288, 0, 0, 0, 0.6*0.25/992, 0.4*0.2565100, 0, 0, 0.5*0.25/160, 0.5*0.25/10500, 0, 0, 0.3*0.25/320, 0.7*0.25/21000)
const.mat<-matrix(c(1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,

                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
                    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,

                    1, 5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357,
                    1, 5.8112, 78.2357, -0.5357,  1, 5.8112, 78.2357, -0.5357

                  ), nrow=33, byrow=TRUE)
const.dir<-c(">=",  "<=", ">=",  "<=",   ">=",  "<=",  ">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",
             "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",
             "<=",">=",  "<=",">=",  "<=",">=",  "<=",">=",  "<=",  "<=")
const.rhs<-c(3*1492.1775, 9*1492.1775, 3*52.0110241252596, 9*52.0110241252596, 3*8.28694679661288, 9*8.28694679661288,
            3*416.601693561272, 9*416.601693561272, 11*1492.1775, 31*1492.1775, 11*52.0110241252596, 31*52.0110241252596,
            11*8.28694679661288, 31*8.28694679661288, 11*416.601693561272, 31*416.601693561272, 3*1492.1775, 5*1492.1775,
            3*52.0110241252596, 5*52.0110241252596, 3*8.28694679661288, 5*8.28694679661288,
            3*416.601693561272, 5*416.601693561272, 1*1492.1775, 10*1492.1775, 1*52.0110241252596, 10*52.0110241252596,
            1*8.28694679661288, 10*8.28694679661288, 1*416.601693561272, 10*416.601693561272, 50000)
Res<-lp("max", objective.in, const.mat, const.dir, const.rhs)

Warning message in rbind(const.mat, const.dir.num, const.rhs):
“number of columns of result is not a multiple of vector length (arg 2)”


In [85]:
Res$solution

[1]  4476.53250   468.09922    74.58252  1249.80508 16413.95250  1612.34175
 [7]   256.89535 12914.65250  4476.53250   260.05512    41.43473  2083.00847
[13]  1492.17750   520.11024    82.86947  4166.01694

In [86]:
HH1(Res$solution);HH2(Res$solution)

[1] 68205.68

[1] 1325.356

In [87]:
opt<-c(4476.5325, 468.099217127336, 74.5825211695159, 1249.80508068382, 16413.9525, 1612.34174788305, 256.895350694999, 12914.6525003994,
4476.5325, 260.055120626298, 41.4347339830644, 2083.00846780636, 1492.1775, 520.110241252596, 82.8694679661288, 4166.01693561272)

In [88]:
num_del = 1492.1775
N1 = ceiling(4476.5325 / num_del )
N2 = ceiling(16413.9525 / num_del )
N3 = ceiling(4476.5325 / num_del )
N4 = ceiling(1492.1775 / num_del )

In [89]:
N1;N2;N3;N4

[1] 3

[1] 11

[1] 3

[1] 1

In [90]:
speed1 = ceiling(468.099217127336 / N1 )
speed2 = ceiling(1612.34174788305 / N2 )
speed3 = ceiling(260.055120626298 / N3 )
speed4 = ceiling(520.110241252596 / N4 )

In [91]:
ram1 = ceiling(74.5825211695159 / N1 )
ram2 = ceiling(256.895350694999 / N2 )
ram3 = ceiling(41.4347339830644 / N3 )
ram4 = ceiling(82.8694679661288 / N4 )

In [92]:
hd1 = ceiling(1249.80508068382  / N1 )
hd2 = ceiling(12914.6525003994  / N2 )
hd3 = ceiling(2083.00846780636 / N3 )
hd4 = ceiling(4166.01693561272 / N4 )

In [93]:
speed1;speed2;speed3;speed4

[1] 157

[1] 147

[1] 87

[1] 521

In [94]:
ram1;ram2;ram3;ram4

[1] 25

[1] 24

[1] 14

[1] 83

In [95]:
hd1;hd2;hd3;hd4

[1] 417

[1] 1175

[1] 695

[1] 4167

In [96]:
distance<-function(A, B){
    return(sqrt(sum((A-B)^2)))}

In [97]:
opt1<-c( speed1,hd1 , ram1)

In [98]:
min_dist<-99999999999999
min_i<-0
for (i in rownames(Data_funcs)){
    dist<-distance(opt1, Data_funcs[i,c(3:5)])
    if (dist < min_dist) {
        min_dist <- dist
        min_i <- i
    }}

In [99]:
min_dist

[1] 58.74521

In [100]:
Data_funcs[min_i,]

X    price speed hd  ram screen cd  multi premium ads trend W1        
3777 3777 2818  100   428 16  17     yes no    yes     273 18    0.09444444
     W2         W3         W4         H1       H2        
3777 0.01230722 0.07038095 0.02926667 12383.16 0.05159982

In [101]:
opt1<-c( speed1,hd1 , ram1)

In [102]:
mmax<-max(Data_funcs$speed); mmin<-min(Data_funcs$speed)
CC1<-(Data_funcs$speed-mmin)*100/(mmax-mmin)
speed1_norm <- (speed1-mmin)*100/(mmax-mmin)
speed2_norm <- (speed2-mmin)*100/(mmax-mmin)
speed3_norm <- (speed3-mmin)*100/(mmax-mmin)
speed4_norm <- (speed4-mmin)*100/(mmax-mmin)

mmax<-max(Data_funcs$hd); mmin<-min(Data_funcs$hd)
CC2<-(Data_funcs$hd-mmin)*100/(mmax-mmin)
hd1_norm <- (hd1-mmin)*100/(mmax-mmin)
hd2_norm <- (hd2-mmin)*100/(mmax-mmin)
hd3_norm <- (hd3-mmin)*100/(mmax-mmin)
hd4_norm <- (hd4-mmin)*100/(mmax-mmin)

mmax<-max(Data_funcs$ram); mmin<-min(Data_funcs$ram)
CC3<-(Data_funcs$ram-mmin)*100/(mmax-mmin)
ram1_norm <- (ram1-mmin)*100/(mmax-mmin)
ram2_norm <- (ram2-mmin)*100/(mmax-mmin)
ram3_norm <- (ram3-mmin)*100/(mmax-mmin)
ram4_norm <- (ram4-mmin)*100/(mmax-mmin)


In [103]:
Data_norm <-data.frame(Data_funcs, CC1, CC2, CC3)
head(Data_norm)

X price speed hd  ram screen cd multi premium ads trend W1        
1 1 1499  25     80  4  14     no no    yes     94  1     0.02361111
2 2 1795  33     85  2  14     no no    yes     94  1     0.02775000
3 3 1595  25    170  4  15     no no    yes     94  1     0.02361111
4 4 1849  25    170  8  14     no no    no      94  1     0.02777778
5 5 3295  33    340 16  14     no no    yes     94  1     0.04233333
6 6 3695  66    340 16  14     no no    yes     94  1     0.06800000
  W2          W3         W4          H1        H2         CC1      CC2       
1 0.002910906 0.01630952 0.006416667  7630.177 0.01231205  0.00000  0.0000000
2 0.001731951 0.01029762 0.004708333  7179.536 0.01112198 10.66667  0.2475248
3 0.003463902 0.02059524 0.009416667  7437.325 0.01427173  0.00000  4.4554455
4 0.005883257 0.03309524 0.013166667  8689.096 0.01998073  0.00000  4.4554455
5 0.011766513 0.06619048 0.026333333 11014.321 0.03665591 10.66667 12.8712871
6 0.011766513 0.06619048 0.026333333 11781.400 0.04307258 54.66667 12.8712871
  CC3      
1  6.666667
2  0.000000
3  6.666667
4 20.000000
5 46.666667
6 46.666667

In [104]:
opt1<-c( speed1_norm,hd1_norm , ram1_norm)

In [105]:
min_dist<-99999999999999
min_i<-0
for (i in rownames(Data_norm)){
    dist<-distance(opt1, Data_norm[i,c(18:20)])
    if (dist < min_dist) {
        min_dist <- dist
        min_i <- i
    }}

In [106]:
min_dist

[1] 81.36394

In [107]:
min_i

[1] "3797"

In [108]:
Data_norm[min_i,]

X    price speed hd   ram screen cd  multi premium ads trend W1       
3797 3797 3543  100   1000 24  14     yes yes   yes     273 18    0.1027778
     W2         W3       W4         H1       H2         CC1 CC2      CC3     
3797 0.02066052 0.122619 0.05583333 13661.02 0.07547267 100 45.54455 73.33333

In [109]:
opt1

[1] 176.00000  16.68317  76.66667

In [110]:
speed1;hd1 ; ram1

[1] 157

[1] 417

[1] 25

In [111]:
opt1<-c( speed2_norm,hd2_norm , ram2_norm)
min_dist<-99999999999999
min_i<-0
for (i in rownames(Data_norm)){
    dist<-distance(opt1, Data_norm[i,c(18:20)])
    if (dist < min_dist) {
        min_dist <- dist
        min_i <- i
    }}

In [112]:
min_dist

[1] 62.67889

In [113]:
Data_norm[min_i,]

X    price speed hd   ram screen cd  multi premium ads trend W1       
6000 6000 2645  100   1200 24  15     yes no    yes     75  30    0.1027778
     W2        W3        W4     H1       H2         CC1 CC2      CC3     
6000 0.0218894 0.1321429 0.0625 13232.46 0.07982751 100 55.44554 73.33333

In [114]:
opt1;speed1;hd1 ; ram1

[1] 162.66667  54.20792  73.33333

[1] 157

[1] 417

[1] 25

In [115]:
opt1<-c( speed3_norm,hd3_norm , ram3_norm)
min_dist<-99999999999999
min_i<-0
for (i in rownames(Data_norm)){
    dist<-distance(opt1, Data_norm[i,c(18:20)])
    if (dist < min_dist) {
        min_dist <- dist
        min_i <- i
    }}

In [116]:
min_dist

[1] 17.41972

In [117]:
Data_norm[min_i,]

X    price speed hd  ram screen cd  multi premium ads trend W1   
5646 5646 2095  75    730 16  15     yes yes   yes     163 27    0.075
     W2         W3        W4         H1       H2         CC1      CC2     
5646 0.01416283 0.0847619 0.03933333 11154.91 0.05331452 66.66667 32.17822
     CC3     
5646 46.66667

In [118]:
opt1;speed1;hd1 ; ram1

[1] 82.66667 30.44554 40.00000

[1] 157

[1] 417

[1] 25

In [119]:
opt1<-c( speed4_norm,hd4_norm , ram4_norm)
min_dist<-99999999999999
min_i<-0
for (i in rownames(Data_norm)){
    dist<-distance(opt1, Data_norm[i,c(18:20)])
    if (dist < min_dist & Data_norm[i,8]=="yes") {
        min_dist <- dist
        min_i <- i
    }}

In [120]:
min_dist

[1] 612.6557

In [121]:
Data_norm[min_i,]

X    price speed hd   ram screen cd  multi premium ads trend W1       
6205 6205 2723  100   1200 24  15     yes yes   yes     39  34    0.1027778
     W2        W3        W4     H1       H2         CC1 CC2      CC3     
6205 0.0218894 0.1321429 0.0625 13232.46 0.07982751 100 55.44554 73.33333

In [122]:
opt1;speed1;hd1 ; ram1

[1] 661.3333 202.3267 270.0000

[1] 157

[1] 417

[1] 25

In [123]:
N1;N2;N3;N4

[1] 3

[1] 11

[1] 3

[1] 1